export enum ErrorMessage {
  CategoryExists = 'Categoria já existente',
  ProductExists = 'Produto já existente',
  UserNotFound = 'Usuário filtrado não encontrado',
  UsersNotFound = 'Usuários não encontrados',
  CategoryNotFound = 'Categoria informada não encontrada',
  CategoriesNotFound = 'Categorias não encontradas',
  ProductNotFound = 'Produto não encontrado',
  ProductsNotFound = 'Produtos não encontrados',
  OrdersNotFound = 'Pedidos não encontrado',
  CategoryNotExists = 'Categoria já deletada ou inexistente',
  ProductNotExists = 'Produto já deletado ou inexistente',
  OrderNotExists = 'Pedidos já deletado ou inexistente',
  OrderItemNotExists = 'Item do pedido já deletado ou inexistente',
  ProductDeleted = 'Produto deletado com sucesso',
  OrderNotFound = 'Pedido não encontrado',
  PaymentNotFound = 'Não foi possível atualizar o pagamento',
  PaymentMethodNotValid = 'Método de pagamento não é válido',
  EmailNotValid = 'E-mail deve ser válido (sendo incluso no mesmo um dos dominios listados: @gmail.com, @hotmail.com, @yahoo.com, @outlook.com, @live.com, @fiap.com) para que o cadastro seja efetuado',
  SocialSecurityNumberNotValid = 'CPF informado não é válido',
  ParametersNotValid = 'Informe os parâmetros corretamentos para a requisição',
  PropertyNotValid = 'Valor da propriedade informada não é válida',
  ErrorUpdateCategory = 'Ocorreu um erro ao atualizar a categoria'
}
