export enum Field {
  Name = 'nome',
  Description = 'descrição',
  CustomerIdentifier = 'identificador do cliente',
  ProductIdentifier = 'identificador do produto',
  OrderIdentifier = 'identificador do pedido',
  UserIdentifier = 'identificador do usuário',
  OrderItem = 'item do pedido',
  Quantity = 'quantidade',
  Method = 'método',
  CategoryIdentifier = 'identificador da categoria',
  Price = 'preço',
  Email = 'email',
  Amount = 'quantia',
  TransactionAmount = 'quantia da transação',
  Status = 'status',
  Size = 'tamanho',
  Category = 'categoria',
  User = 'usuário',
  Order = 'pedido',
  SocialSecurityNumber = 'CPF'
}
