export enum Field {
  Amount = 'quantia',
  Category = 'categoria',
  CategoryIdentifier = 'identificador da categoria',
  CustomerIdentifier = 'identificador do cliente',
  Description = 'descrição',
  Email = 'email',
  Method = 'método',
  Name = 'nome',
  Observation = 'observação',
  Order = 'pedido',
  OrderItem = 'item do pedido',
  OrderIdentifier = 'identificador do pedido',
  Payment = 'pagamento',
  PaymentMethod = 'método de pagamento',
  Price = 'preço',
  Product = 'produto',
  ProductIdentifier = 'identificador do produto',
  Quantity = 'quantidade',
  Size = 'tamanho',
  SocialSecurityNumber = 'CPF',
  Status = 'status',
  TransactionAmount = 'quantia da transação',
  User = 'usuário',
  UserIdentifier = 'identificador do usuário'
}
